In [1]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt

In [2]:
someConst = tf.constant([3, 5.0])

In [3]:
print(someConst)

tf.Tensor([3. 5.], shape=(2,), dtype=float32)


In [4]:
someConst.numpy()

array([3., 5.], dtype=float32)

In [5]:
someVariable = tf.Variable(np.arange(5, dtype=np.float64))
someVariable

<tf.Variable 'Variable:0' shape=(5,) dtype=float64, numpy=array([0., 1., 2., 3., 4.])>

In [6]:
someVariable.numpy()

array([0., 1., 2., 3., 4.])

In [7]:
a = np.arange(10)
b = np.arange(10)

c = tf.add(a, b)

In [8]:
c

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])>

In [9]:
print(f"{a}\n+{b}\n=\n{c}")

[0 1 2 3 4 5 6 7 8 9]
+[0 1 2 3 4 5 6 7 8 9]
=
[ 0  2  4  6  8 10 12 14 16 18]


In [10]:
a = np.arange(10).reshape(10,1)
b = np.arange(10).reshape(1,10)

c = tf.matmul(a,b)

In [11]:
print(f"{a}\n*{b}\n=\n{c}")

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
*[[0 1 2 3 4 5 6 7 8 9]]
=
[[ 0  0  0  0  0  0  0  0  0  0]
 [ 0  1  2  3  4  5  6  7  8  9]
 [ 0  2  4  6  8 10 12 14 16 18]
 [ 0  3  6  9 12 15 18 21 24 27]
 [ 0  4  8 12 16 20 24 28 32 36]
 [ 0  5 10 15 20 25 30 35 40 45]
 [ 0  6 12 18 24 30 36 42 48 54]
 [ 0  7 14 21 28 35 42 49 56 63]
 [ 0  8 16 24 32 40 48 56 64 72]
 [ 0  9 18 27 36 45 54 63 72 81]]


In [12]:
a = np.arange(10).reshape(1,10)
b = np.arange(10).reshape(10,1)

c = tf.matmul(a,b)
print(f"{a}\n*{b}\n=\n{c}")

[[0 1 2 3 4 5 6 7 8 9]]
*[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
=
[[285]]


In [13]:
# Budowanie modelu


In [14]:
# dane wejsciowe
X = np.array([
    [1,1],
    [1,0],
    [0,1],
    [0,0]   
], dtype=np.float32)
X

array([[1., 1.],
       [1., 0.],
       [0., 1.],
       [0., 0.]], dtype=float32)

In [15]:
# dane wyjściowe
Y = np.array([
    0,
    1,
    1,
    0
], dtype=np.float32)
Y

array([0., 1., 1., 0.], dtype=float32)

In [16]:
#Warstwy

In [17]:
from tensorflow.keras import layers

In [18]:
inputLayer = layers.InputLayer(input_shape=(10))

In [19]:
inputLayer(tf.ones(10))

<tf.Tensor: shape=(10,), dtype=float32, numpy=array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32)>

In [20]:
denseLayer = layers.Dense(5)

In [21]:
denseLayer(tf.ones(shape=(1,2)))

<tf.Tensor: shape=(1, 5), dtype=float32, numpy=
array([[-0.46501744,  1.0949435 , -0.2805295 ,  0.04187983, -0.2826606 ]],
      dtype=float32)>

In [22]:
actLayer = layers.Activation('relu')

In [23]:
actLayer(denseLayer(tf.ones(shape=(1,2))))

<tf.Tensor: shape=(1, 5), dtype=float32, numpy=
array([[0.        , 1.0949435 , 0.        , 0.04187983, 0.        ]],
      dtype=float32)>

In [24]:
softLayer = layers.Softmax()

In [25]:
softLayer(np.array([2,4,8,10], dtype=np.float32))

<tf.Tensor: shape=(4,), dtype=float32, numpy=
array([2.94743892e-04, 2.17787945e-03, 1.18908174e-01, 8.78619194e-01],
      dtype=float32)>

In [26]:
dropLayer = layers.Dropout(0.2)

In [27]:
tmpArr = np.arange(10).astype(np.float32)
tmpArr

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

In [28]:
dropLayer(tmpArr, training=True).numpy()

array([ 0.  ,  1.25,  2.5 ,  3.75,  5.  ,  0.  ,  7.5 ,  8.75,  0.  ,
       11.25], dtype=float32)

In [29]:
model = tf.keras.Sequential()

In [30]:
model.add(layers.InputLayer(input_shape=(2)))

In [31]:
model.add(layers.Dense(10))

In [32]:
model.add(layers.Activation('relu'))

In [33]:
model.add(layers.Dense(1))

In [34]:
model.add(layers.Activation('sigmoid'))

In [35]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_1 (Dense)             (None, 10)                30        
                                                                 
 activation_1 (Activation)   (None, 10)                0         
                                                                 
 dense_2 (Dense)             (None, 1)                 11        
                                                                 
 activation_2 (Activation)   (None, 1)                 0         
                                                                 
Total params: 41
Trainable params: 41
Non-trainable params: 0
_________________________________________________________________


In [36]:
#trening modelu

In [37]:
optimizer = tf.keras.optimizers.SGD(learning_rate=0.01)

In [38]:
loss = tf.keras.losses.MeanSquaredError()

In [39]:
model.compile(
    optimizer=optimizer,
    loss=loss
)

In [40]:
results = model.fit(
    x = X,
    y = Y,
    epochs = 10000,
    verbose=0
)

In [41]:
results.history.keys()

dict_keys(['loss'])

In [42]:
# fig = plt.figure(figsize=(20,10))
# plt.plot(results.history['loss'])
# plt.xlabel('Epochs')
# plt.ylabel('Loss')
# plt.title('MSE through training')
# plt.show()


In [43]:
model = tf.keras.Sequential()
model.add(layers.InputLayer(input_shape=(2)))
model.add(layers.Dense(10))
model.add(layers.Activation('relu'))
model.add(layers.Dense(1))
model.add(layers.Activation('sigmoid'))
model.summary()

optimizer = tf.keras.optimizers.SGD(learning_rate=10)
loss = tf.keras.losses.MeanSquaredError()
model.compile(
    optimizer=optimizer,
    loss=loss
)

results = model.fit(
    x = X,
    y = Y,
    epochs = 100,
    verbose=0
)



Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_3 (Dense)             (None, 10)                30        
                                                                 
 activation_3 (Activation)   (None, 10)                0         
                                                                 
 dense_4 (Dense)             (None, 1)                 11        
                                                                 
 activation_4 (Activation)   (None, 1)                 0         
                                                                 
Total params: 41
Trainable params: 41
Non-trainable params: 0
_________________________________________________________________


In [44]:
# fig = plt.figure(figsize=(20,10))
# plt.plot(results.history['loss'])
# plt.xlabel('Epochs')
# plt.ylabel('Loss')
# plt.title('MSE through training')
# plt.show()

In [45]:
model = tf.keras.Sequential()
model.add(layers.InputLayer(input_shape=(2)))
model.add(layers.Dense(10))
model.add(layers.Activation('relu'))
model.add(layers.Dense(1))
model.add(layers.Activation('sigmoid'))
model.summary()

optimizer = tf.keras.optimizers.SGD(learning_rate=0.5)
loss = tf.keras.losses.MeanSquaredError()
model.compile(
    optimizer=optimizer,
    loss=loss
)

results = model.fit(
    x = X,
    y = Y,
    epochs = 500,
    verbose=0
)


Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_5 (Dense)             (None, 10)                30        
                                                                 
 activation_5 (Activation)   (None, 10)                0         
                                                                 
 dense_6 (Dense)             (None, 1)                 11        
                                                                 
 activation_6 (Activation)   (None, 1)                 0         
                                                                 
Total params: 41
Trainable params: 41
Non-trainable params: 0
_________________________________________________________________


In [46]:
# fig = plt.figure(figsize=(20,10))
# plt.plot(results.history['loss'])
# plt.xlabel('Epochs')
# plt.ylabel('Loss')
# plt.title('MSE through training')
# plt.show()

In [47]:
results.history['loss'][-1]

0.003450875636190176

In [48]:
#walidacja, sprawdzenie czy model dobrze sie nauczył

In [49]:
model.evaluate(
    x=X, 
    y=Y
)

1/1 [==============================] - 0s 261ms/step - loss: 0.0034


0.0034404643811285496

In [50]:
y_pred = model.predict(X)
y_pred

1/1 [==============================] - 0s 156ms/step


array([[0.02864719],
       [0.95905775],
       [0.95889646],
       [0.09785412]], dtype=float32)

In [51]:
Y

array([0., 1., 1., 0.], dtype=float32)

In [52]:
np.greater(y_pred, 0.5).astype(np.int32)  #sprawdzenie czy model zwrócił dobre wartości, 
                                          #odpowiedzi wyświetlone w wartościach liczbowych int więc 0 to Fals a 1 to True

array([[0],
       [1],
       [1],
       [0]])

In [53]:
model.predict(X[1].reshape(1,2))

1/1 [==============================] - 0s 49ms/step


array([[0.95905775]], dtype=float32)

In [54]:
model.predict([[0,1]])

1/1 [==============================] - 0s 138ms/step


array([[0.95889646]], dtype=float32)

In [55]:
model.predict([[0,2]])

1/1 [==============================] - 0s 85ms/step


array([[0.9991469]], dtype=float32)

In [56]:
model.predict([[5,5]])

1/1 [==============================] - 0s 93ms/step


array([[4.756236e-07]], dtype=float32)

In [57]:
## Dodawanie warstw

In [72]:
model = tf.keras.Sequential()

In [73]:
model.add(layers.InputLayer(input_shape=(2), name="wejscie"))

In [74]:
model.add(layers.Dense(1024, activation='relu', name='ukryta_pierwsza'))

In [75]:
model.add(layers.Dense(512, activation='relu', name='ukryta_druga'))

In [76]:
model.add(layers.Dense(256, activation='relu', name='ukryta_trzecia'))

In [77]:
model.add(layers.Dense(1, activation='sigmoid', name='wyjscie'))

In [78]:
model.compile(
    optimizer=tf.keras.optimizers.SGD(learning_rate=0.1),
    loss=tf.keras.losses.MeanSquaredError()
)

In [79]:
model.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 ukryta_pierwsza (Dense)     (None, 1024)              3072      
                                                                 
 ukryta_druga (Dense)        (None, 512)               524800    
                                                                 
 ukryta_trzecia (Dense)      (None, 256)               131328    
                                                                 
 wyjscie (Dense)             (None, 1)                 257       
                                                                 
Total params: 659,457
Trainable params: 659,457
Non-trainable params: 0
_________________________________________________________________


In [80]:
##trening rozszerzonego modelu

In [81]:
results = model.fit(
    x = X,
    y = Y,
    epochs = 500,
    verbose=0
)

# fig = plt.figure(figsize=(20,10))
# plt.plot(results.history['loss'])
# plt.xlabel('Epochs')
# plt.ylabel('Loss')
# plt.title('MSE through training')
# plt.show()

In [82]:
## Rzeczywiste funkcjonowanie modelu


In [83]:
y_pred = model.predict(X)
y_pred

1/1 [==============================] - 0s 125ms/step


array([[0.03601408],
       [0.9587921 ],
       [0.9595993 ],
       [0.07098251]], dtype=float32)

In [84]:
np.greater(y_pred, 0.5).astype(np.int32)

array([[0],
       [1],
       [1],
       [0]])

In [85]:
## Archiwizacja modelu

In [86]:
model.save(filepath='model')

INFO:tensorflow:Assets written to: model\assets


In [87]:
ls model

 Volume in drive C is OS
 Volume Serial Number is 5C45-5B08

 Directory of C:\Users\piotr\model

07.03.2023  20:46    <DIR>          .
07.03.2023  20:46    <DIR>          ..
07.03.2023  20:46    <DIR>          assets
07.03.2023  20:46            10˙021 keras_metadata.pb
07.03.2023  20:46            89˙202 saved_model.pb
07.03.2023  20:46    <DIR>          variables
               2 File(s)         99˙223 bytes
               4 Dir(s)  571˙536˙588˙800 bytes free


In [88]:
## Wczytanie modelu

In [89]:
loaded_model = tf.keras.models.load_model(
    filepath = 'model'
)

In [90]:
loaded_model.evaluate(
    x=X,
    y=Y
)

1/1 [==============================] - 0s 180ms/step - loss: 0.0024


0.0024164605420082808

In [92]:
loaded_model.predict(X)

1/1 [==============================] - 0s 98ms/step


array([[0.03601408],
       [0.9587921 ],
       [0.9595993 ],
       [0.07098251]], dtype=float32)

In [94]:
results = loaded_model.fit(
    x=X,
    y=Y,
    epochs=5
)

Epoch 1/5
1/1 [==============================] - 1s 1s/step - loss: 0.0024
Epoch 2/5
1/1 [==============================] - 0s 10ms/step - loss: 0.0024
Epoch 3/5
1/1 [==============================] - 0s 10ms/step - loss: 0.0024
Epoch 4/5
1/1 [==============================] - 0s 7ms/step - loss: 0.0024
Epoch 5/5
1/1 [==============================] - 0s 9ms/step - loss: 0.0024
